import '@/styles/globals.css'
import type { AppProps } from 'next/app'

// nextjs
import Head from 'next/head'

// config
import { Provider as ReduxProvider } from 'react-redux'
import reduxStore from "../src/config/reduxStore"

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ReduxProvider store={reduxStore}>
      <Head>
        <title>DeDisk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Component {...pageProps} />
    </ReduxProvider>
  )
}
